### ISSUE TITLE
Support Variables and Keywords in resource files recursively

### ISSUE THREAD

**Issue by deaglejv** [millennialmedia/intellibot#102]
Scenario:

File 1 has a resource of R1
File 2 has a resource of File 1

When I enter variables or keywords that are in R1 in File 2, they are listed as cannot find in the IDE.

Enhancement to identify variables and keywords defined in resource chains.

**Comment by mtrubs** [comment]
do you have the latest version (0.6.7)?  This should handle that.

**Comment by mtrubs** [comment]
should be #89
