### ISSUE TITLE
Unable to auto-complete custom python-based keywords

### ISSUE THREAD

**Issue by boakley** [millennialmedia/intellibot#107]
I don't know if this is a documentation issue or a functionality issue, but I can't figure out how to get pycharm to autocomplete on my custom keywords. 

I have an import that looks like this:

    *** Settings ***
    Library    pages.product.LoginPage

The file "LoginPage.py" implements a class named "LoginPage", and it has several keywords in it. When I run robot, I add the --pythonpath option to include the parent of the "pages" folder. It all works fine.

If I right-click on that library in pycharm and select "go to declaration", pycharm is able to find the file and load it into the editor. This makes me think it's able to find and parse the file. Yet, if I start typing a keyword from that file, no autocomplete information is available. 

I'm only a casual PyCharm user, so I don't know if I should edit some sort of plugin, project, or global settings. There's simply no documentation anywhere that shows how to get the plugin to recognize local class-based keywords. 

Note:  if I use the other robotframework plugin, the autocomplete works, but then I lost the ability to jump to the implementation.

**Comment by mtrubs** [comment]
dup of i think #65 so fixed in #110
