### ISSUE TITLE
Autocomplete and Documentation does not work for Libraries imported from Resources

### ISSUE THREAD

**Issue by markwinspear** [millennialmedia/intellibot#111]
In a page object model scenario, If I create a BasePage.robot file which imports the Selenium2Library (because I will need it in all of my pages, I don't want to import it every time), i.e.

*** Settings***
Library  Selenium2Library

If I subsequently create pages which use this base page, i.e.
*** Settings ***
Resource    ${CURDIR}/BasePage.robot

If I do this, autocomplete does not work. Selecting documentation from a keyword also does not work.

The only way I can make this work is to import the Selenium2Library on all pages

This looks like a bug to me.

**Comment by mtrubs** [comment]
1) Do you have the 'Allow transitive imports' option checked in your Preferences?
![screen shot 2015-10-21 at 3 06 14 pm](https://cloud.githubusercontent.com/assets/4164266/10647360/c7686a60-7805-11e5-83af-cb36c0963108.png)

2) Does this work if you do not use the CURDIR variable?  See #104

**Comment by markwinspear** [comment]
Thanks for the relpy
1, Yes, it is checked
2. Yes, it works if I remove CURDIR

**Comment by mtrubs** [comment]
duplicates #104
