### ISSUE TITLE
CPU problems

### ISSUE THREAD

**Issue by yahman72** [millennialmedia/intellibot#113]
intellibot doesn't seem to be able to deal with robot/resource files if they are relatively big.

When I open a resource file that has ~1K lines of code (keywords) the CPU utilization goes up to 25-30% and stays there as long as I'm not doing anything with the IDE.
If I press ctrl+space (i.e. autocomplete window shows up) the CPU utilization goes down to 5%.
--> is there some sort of background scanning that it always on?

I also have big test suite (i.e. robot file) with >5K lines of code, if I open that one and have a couple of resource files open then the CPU load is permanently ~80% and if I try to edit those files the CPU goes over 90% and the editor becomes sluggy (there's 0,5s of delay after typing a key)

I have this problem on two PCs, one desktop with intel i5 (and 4GB of RAM) and a laptop also with i5 (and 8GB of RAM)

**Comment by mtrubs** [comment]
I am not sure if there is a good way for me at address this.  Do you know if the slowdown happens during the parsing of the file for syntax (coloring), the resolving of keywords and such or the inspections?  You might be able to tell based on what the IDE is doing.  There is caching that happens, but these large files might just be too large.

Refactoring your code into smaller files should help.  The project we have has multiple hundreds of files, though they are not quite as large as you mention (100-200 lines i would say).  This way the IDE does not have to parse it all in one go, more as encountered.  Though one of our project's files pulls in others so and so forth, so it fans out quickly.  But the IDE never grinds to a halt.  I think that is part of it.  Plus a change in the file would cause it to have to parse and analyze parts of it again.

Note that in some cases the IDE has crashed when there are unexepected combinations of parsing.   Somehow it gets into infinite loops of sorts.  Something more like #103.

**Comment by yahman72** [comment]
Don't know when this happens - is there a possibiliy to enable some logging/profiling to see what's happening?

I don't think that this is only because of large files - if it would be so then the CPU load should be less after a while (i.e. after all parsing+coloring etc. is done). In my case the CPU load is permanently high = the plugin does something all the time. 

Does intellibot detect "circular" imports? E.g. `file-A imports file-B` + `file B imports file-C` + `file C imports file-A`. If not, this could cause an infite parsing loop ... 

PS.
The IDE doesn't crash or freeze, it just becomes sluggish i.e. you can still work with it, but the response times are not what they should be...

**Comment by mtrubs** [comment]
yes i think the case of a circular import is covered, but I will check.

You can enable profiling of sorts in the Robot Options.  Data will then start to be logged into the Event Log.  This will show what sort of files the IDE is looking for as well as timing for parsing of various parts.  I need to add this to the wiki, but here are the screen shots.

![screen shot 2015-11-10 at 9 09 33 am](https://cloud.githubusercontent.com/assets/4164266/11064953/84a83a5a-878e-11e5-8b68-f2f6bada8b5c.png)

![screen shot 2015-11-10 at 9 20 33 am](https://cloud.githubusercontent.com/assets/4164266/11064955/891a81e2-878e-11e5-995f-be4166420509.png)

**Comment by mtrubs** [comment]
https://github.com/millennialmedia/intellibot/wiki/Robot-Options

**Comment by yahman72** [comment]
thanks, I'll have look at this. Will take a couple of days because I'm busy with other stuff...

**Comment by yahman72** [comment]
There doesn't seem to be anything special in the event log:
There are the usual `[RobotFileManager]` "attempting..." etc. logs
The only suspicious entry is this: 
`07:31:03 Debug: [largeFile.robot][resolve][My Keyword] 999ms`

But for some reason the CPU load is now constantly ~40% = IDE is responsive, 40% is still quite much, but those peaks >80% are not occurring. I'll keep the debug trace on and let you know if the IDE becomes sluggish again...

**Comment by yahman72** [comment]
I have had the logs on for some time, and the IDE also been sluggish quite a few times. 
There's nothing suspicious in the logs, the above example could be complemented like this:
`07:31:03 Debug: [test suite or resource file][resolve][A Keyword or Variable] <anything up to 15000>ms`

This could also be generic issue with PyCharm - I found some articles about PyCharm performance issues in general, e.g.
https://devnet.jetbrains.com/docs/DOC-1212
https://intellij-support.jetbrains.com/hc/en-us/articles/206827577-Reporting-performance-problems

I'll have a look at those and see if they bring help...

**Comment by mtrubs** [comment]
So in the cases where the is >10000ms, are those particularly buried keywords, like an import of import of an import? or an import of a particularly large file or something? is there a common link between the long parsing items?

**Comment by yahman72** [comment]
Nope, mostly direct imports and at most import of an import. 

There's also one slightly different debug log:
`09:41:09 Debug: [resourcefile_1500lines.txt][files from invoked keywords][*** Keywords ***] 209688ms`

**Comment by mtrubs** [comment]
i will take a look at code around that area.

Does the 1500 line file import multiple other 1500 line files?

**Comment by yahman72** [comment]
No, only some standard Libraries (Collections, etc.)

**Comment by mtrubs** [comment]
I fixed a couple of issues around end of file errors.  this was giving me some IDE sluggishness.  It is hard to say if this will correct your issue without getting my hands on the file.

**Comment by yahman72** [comment]
Thanks for the info, in which release are those fixes?

Some updates on my side:
- Meanwhile I'm on PyCharm 5.0.3 and Intellibot 0.6.9
- I refactored my test suites (i.e. that >5K lines file), the IDE hasn't been sluggish for a while but there are still long resolution times e.g. `10:42:20 Debug: [suite_with_300_lines.robot][files from invoked keywords][*** Test Cases ***] 168857ms`
- the above suite imports directly 1 "common" resource file (with 600 LoC), 4 resource files (with 1800, 400, 1600 & 300 LoC) and some standard libs
- those 4 resource files all import that "common" resource file

**Comment by mtrubs** [comment]
That would be the most current release 0.8.x
