### ISSUE TITLE
Functionality for display of File Structure

### ISSUE THREAD

**Issue by lkirwan** [millennialmedia/intellibot#120]
IntelliJ has a very useful feature, File Structure (screenshot below), to display a list of the contents of a file in table-of-contents format.  It would be great if intellibot could integrate with this.

![example](https://cloud.githubusercontent.com/assets/86779/11336060/1a4bcf4a-91da-11e5-8c49-34990c423821.png)

**Comment by mtrubs** [comment]
yes, that certainly looks like a good thing to implement.  just a matter of finding the right hooks in the IDE code.  I'll investigate.

**Comment by ovkhasch** [comment]
lang.psiStructureViewFactory extension point

**Comment by mtrubs** [comment]
will check that out; thanks for the head start!

**Comment by lkirwan** [comment]
that's brilliant, thanks.  When I get a chance I'll set up my environment to get familiar with this code.  Much appreciated.

**Comment by mtrubs** [comment]
I started a first pass at this.  It works but needs polish.

https://github.com/mtrubs/intellibot/commit/091f745f7114666625e5343d3fc056bb6f5d8cac

I cannot tell, but if you were looking to contribute that might get you part of the way.

Things I still have to do would be sorting/filtering, maybe some better icons, and of course the jump to source action?

![screen shot 2015-11-25 at 12 00 04 pm](https://cloud.githubusercontent.com/assets/4164266/11403803/d05b13b6-936c-11e5-90b9-f9b7b673412d.png)

**Comment by mtrubs** [comment]
added some polish #129

**Comment by lkirwan** [comment]
this is brilliant, thank you! The added filtering is also very much appreciated!

**Comment by mtrubs** [comment]
Thanks. I appreciate the feedback.  FYI I intentionally did not do a true structure representation of the file. It seemed like many Robot headers were redundant and having multiple groups of keywords was not valuable in my mind. Hence the flatness. Hope it makes sense as people use it.
