### ISSUE TITLE
No Python Support for Robot

### ISSUE THREAD

**Issue by 24mu13** [millennialmedia/intellibot#122]
*OS*: Debian 8.2
*IDE*: IntelliJ Community Edition 15
*Plugin*: Python Community Edition 5
*Python*: Anaconda 2.3

I have the following message while opening my (working) project with a single robot file.
Note: the robot file is in a "tests" sub-folder.. differently I don't get any message like the following.

```
11:52:53 AM Intellibot: No Python Support for Robot: If you configure a python interpreter you will be able to get code completion around imported libraries in your robot files.
```

**Comment by mtrubs** [comment]
If you want to use python based keywords in your robot files you need to configure the interpreter so that things can correctly be found/parsed.  This info bubble appears if you do not have the python plugin installed to let you know you can install and configure it.

https://github.com/millennialmedia/intellibot/wiki/Python-Interpreter

**Comment by 24mu13** [comment]
Yes I have it. As I said I use "Python Community Edition" i.e. PyCharm, not simply "Python"..

**Comment by mtrubs** [comment]
sorry, slightly confused.  Are you using intellij or pycharm?

if intellij, you can install the python plugin to get support.
if pycharm, it should not show this warning and python should already be supported.

**Comment by 24mu13** [comment]
I use IntelliJ and I installed the "Python Community Edition" plugin....

**Comment by mtrubs** [comment]
Ok in that case, the instructions should work for you.  you just need to setup a python sdk and specify it as the interpreter in your project.

**Comment by mtrubs** [comment]
oh wait i see; let me take a look locally.

**Comment by mtrubs** [comment]
so you are saying you have this plugin: (python ce) https://plugins.jetbrains.com/plugin/7322?pr= 
vs this plugin: (python) https://plugins.jetbrains.com/plugin/631?pr=

I should be able to make it so that one or the other is acceptable.

**Comment by 24mu13** [comment]
exactly

**Comment by 24mu13** [comment]
Maybe the reason is that I am using Anaconda as Python SDK....

**Comment by mtrubs** [comment]
if you open a python file in intellij does it resolve correctly or are there a bunch of errors (libs not found, or functions)?

**Comment by 24mu13** [comment]
If I open the referenced (Libraries) Python file, I have no issue.
By the way I verified the same problem in Windows, with the same Python+IDE: Anaconda+IntelliJ Community+Python Community

**Comment by mtrubs** [comment]
Ok.  I am pretty sure that the CE version must have a different plugin and this doesnt get registered.  If python files work fine, then the robot plugin ought to be able to find them.  I just need to get around to downloading the CE version to confirm.

**Comment by mtrubs** [comment]
#128

Juggling between CE and U is such fun :stuck_out_tongue_winking_eye:
