### ISSUE TITLE
Support for "Find Usages"

### ISSUE THREAD

**Issue by rekrabm** [millennialmedia/intellibot#130]
I'd like to request some additional features for this plugin:
- Support for the Structure View on the left pane next to the Project view.
- Support for "Find Usages".
- Fix intentions so they find definitions through Library and Resource references.
- Some clarity on how to configure the environment to support the Intentions provided.  
-    - I'm finding it difficult to resolve the difference between what Pybot does and the warnings that Intellibot gives me.  Pybot works OK while Intellibot finds many unresolved references.  This is, perhaps, down to some path issue, but I'm not sure.

**Comment by mtrubs** [comment]
I am going to change this to 'find usages'.

1) For structure view see #120 (not yet released)
2) Find usages to be this ticket
3/4/5) check this wiki page on how to setup your project.  Regarding python libraries, if your IDE does not resolve those correct, intellibot will have no chance to do so.  Confirming that .py files have no errors is a great first step.  See https://github.com/millennialmedia/intellibot/wiki/Python-Interpreter and let me know if that resolves most of the issues and confusion you are seeing right now.  Lots of people have this question, so I think I need to make that wiki page a little more prominent.

**Comment by mtrubs** [comment]
I will also add that I as super hesitant to implement any sort of refactoring support as I am paranoid that if I missed something I am going to mess up peoples work.  I think I am at the point where I can (mostly) comfortably implement a find usages.  That might help flush out any sort of missed references.

**Comment by ovkhasch** [comment]
Any refactoring in idea can be undone. There's also a local history, so it
is not a big deal. Find usages is typically based on reference resolution,
so it will not add anything to that but it is a very usable feature. For
example, if you implement rename refactoring - it will be the same set of
occurrences that is displayed by find usages, renamed and from which you
are able to navigate to definition, i.e. references are resolvable.

**Comment by ovkhasch** [comment]
BTW, you can also consider implementing "extract keyword", "extract keyword
parameter" and, which is very similar - "extract variable" (assign a
keyword result to a new variable). You can look into python plugin code -
there are good examples of how it can be done.

AFAIK, only small number of advanced users use refactorings. However, these
refactorings may significantly improve the productivity when used with
their hotkeys.

Another simple feature that you can consider is autocompletion for
resource/library paths :)

**Comment by rekrabm** [comment]
Good points.  I’ve always used the preview for refactorings thus having had none of the difficulties I expected. 
Refactorings tend to be heavily used in my org at work.
Autocompletion is highly desirable also because we have a very large code base, growing rapidly, and it’s becoming difficult to know what Robot “keywords” (I still think of them as key phrases) are available.
Kind regards,
Matthew
----
Matthew Barker

**Comment by mtrubs** [comment]
#140
