### ISSUE TITLE
Add autocomplete support for WITH NAME references

### ISSUE THREAD

**Issue by jimni** [millennialmedia/intellibot#141]
Somehow related to #97.
I would very much like to be able to reference libraries using custom names. At this moment plugin fails to recognize a keyword as correct for such library:
<img width="406" alt="286032b0-b3b3-11e5-990e-fc50ae78da5e" src="https://cloud.githubusercontent.com/assets/15658803/12209378/7b97ba36-b663-11e5-80e7-8d39abb4a14e.png">

**Comment by mtrubs** [comment]
can you tell me how this plays out?

```
Import Library  Selenium2Library  WITH NAME  s2l
s2l.Set Selenium Speed  1                   # works in pybot per you example
Selenium2Library.Set Selenium Speed  2      # does this still work or does s2l overwrite it?
```

**Comment by jimni** [comment]
Sure

    No keyword with name 'Selenium2Library.Set Selenium Speed' found.

**Comment by mtrubs** [comment]
sweet. thanks.

**Comment by mtrubs** [comment]
#155
