### ISSUE TITLE
Creation of dictionary variable is marked as error

### ISSUE THREAD

**Issue by aberzan** [millennialmedia/intellibot#144]
Dictionary variables can be created as "&{complexdata}=  Create Dictionary  key1=value1  key2=value2"
In this case it is highlighted as error (keyword definition not found) and future usages of ${complexdata} are marked as well (variable definition not found).

Example:
```
*** Settings ***

*** Variables ***


*** Test Cases ***
Log Dictionary variable
        &{complexvar}=  Create Dictionary  a=aa
        ...                                b=bb
        ...                                c=cc

        log to console  ${complexvar}


```

**Comment by mtrubs** [comment]
Yeah, I definitely have not added &.  I think I just covered `$`, `@` and `%`.  Is `&` interchangeable with `$`?  What is the point/difference in it?

**Comment by aberzan** [comment]
In provided example `&` is interchangeable with `$`. (and will work for me, thanks)
It is NOT interchangeable if we define variable in "Variable" section, e.g.:

```
*** Settings ***

*** Variables ***
&{complexvar}  a=aa  b=bb

*** Test Cases ***
Log Dictionary variable

        log to console  ${complexvar}      # marked with error
        log to console  ${complexvar.a}    # marked with error
```
in this case using `${complexvar}` will create a simple string with `a=aa b=bb` value and `${complexvar.a}` will not work.

The main benefit of using `&` (from user guide):

> There are, however, some actual benefits in creating a dictionary variable explicitly. First of all, Robot Framework verifies that the returned value is a dictionary or dictionary-like similarly as it verifies that list variables can only get a list-like value. Another benefit is that Robot Framework converts the value into a special dictionary it uses also when creating dictionary variables in the variable table. These dictionaries are sortable and their values can be accessed using attribute access like ${dict.first} in the above example.

For me, the fact that this is interchangeable in first/original case, solves the issue.
But still could be an enhancement for future.

**Comment by mtrubs** [comment]
#155
