### ISSUE TITLE
Inspection: "Variable definition not found" for Reserved Variables and Variable syntax

### ISSUE THREAD

**Issue by mtraynham** [millennialmedia/intellibot#150]
These are pretty much all the reserved variables for Robotframework, but the editor flags all of them with the inspection.  Can you just white list these from the inspection?  It'd also be nice if they added context in some cases like ${CURDIR} or ${/}.

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#operating-system-variables

|Variable|Explanation|
|------------|---------------|
|${CURDIR}|An absolute path to the directory where the test data file is located. This variable is case-sensitive.|
|${TEMPDIR}|An absolute path to the system temporary directory. In UNIX-like systems this is typically /tmp, and in Windows c:\Documents and Settings\<user>\Local Settings\Temp.|
|${EXECDIR}|An absolute path to the directory where test execution was started from.|
|${/}|The system directory path separator. / in UNIX-like systems and \ in Windows.|
|${:}|The system path element separator. : in UNIX-like systems and ; in Windows.|
|${\n}|The system line separator. \n in UNIX-like systems and \r\n in Windows. New in version 2.7.5.|

There is a few other one off-cases here:

|Variable|Explanation|
|------------|---------------|
|${80}|Actual number instead of String value|
|${true}|Boolean true|
|${false}|Boolean false|
|${null}|Null|
|${SPACE}|String with space|
|${SPACE * 2}|String with two spaces|
|${EMPTY}|Empty String|
|@{EMPTY}|Empty array|
|&{EMPTY}|Empty dict|

And then this whole table, but scoping matters here:

|Variable|Explanation|Available Scope|
|------------|---------------|--------------|
|${TEST NAME}|	The name of the current test case.	|Test case
|@{TEST TAGS}|	Contains the tags of the current test case in alphabetical order. Can be modified dynamically using Set Tags and Remove Tags keywords.	|Test case
|${TEST DOCUMENTATION}|	The documentation of the current test case. Can be set dynamically using using Set Test Documentation keyword. New in Robot Framework 2.7.	|Test case
|${TEST STATUS}|	The status of the current test case, either PASS or FAIL.	|Test teardown
|${TEST MESSAGE}|	The message of the current test case.	|Test teardown
|${PREV TEST NAME}|	The name of the previous test case, or an empty string if no tests have been executed yet.	|Everywhere
|${PREV TEST STATUS}|	The status of the previous test case: either PASS, FAIL, or an empty string when no tests have been executed.	|Everywhere
|${PREV TEST MESSAGE}|	The possible error message of the previous test case.	|Everywhere
|${SUITE NAME}|	The full name of the current test suite.	|Everywhere
|${SUITE SOURCE}|	An absolute path to the suite file or directory.|	Everywhere
|${SUITE DOCUMENTATION}|	The documentation of the current test suite. Can be set dynamically using using Set Suite Documentation keyword. New in Robot Framework 2.7.	|Everywhere
|&{SUITE METADATA}|	The free metadata of the current test suite. Can be set using Set Suite Metadata keyword. New in Robot Framework 2.7.4.	|Everywhere
|${SUITE STATUS}|	The status of the current test suite, either PASS or FAIL.	|Suite teardown
|${SUITE MESSAGE}|	The full message of the current test suite, including statistics.	|Suite teardown
|${KEYWORD STATUS}|	The status of the current keyword, either PASS or FAIL. New in Robot Framework 2.7	|User keyword teardown
|${KEYWORD MESSAGE}|	The possible error message of the current keyword. New in Robot Framework 2.7.	|User keyword teardown
|${LOG LEVEL}|	Current log level. New in Robot Framework 2.8.	|Everywhere
|${OUTPUT FILE}|	An absolute path to the output file.	|Everywhere
|${LOG FILE}|	An absolute path to the log file or string NONE when no log file is created.	|Everywhere
|${REPORT FILE}|	An absolute path to the report file or string NONE when no report is created.	|Everywhere
|${DEBUG FILE}|	An absolute path to the debug file or string NONE when no debug file is created.	|Everywhere
|${OUTPUT DIR}|	An absolute path to the output directory.	|Everywhere|

**Comment by mtrubs** [comment]
do you know if the underscore is optional?  ie ${OUTPUT_DIR} vs ${OUTPUT DIR}?

**Comment by ovkhasch** [comment]
Underscores and single spaces are disregarded for all variable/keyword
names. It can be ${OUTPUTDIR} too.

**Comment by mtrubs** [comment]
shesh.  the overkill in flexibility in the language is astounding.  :stuck_out_tongue_winking_eye: 

thanks!

**Comment by mtrubs** [comment]
#155
