### ISSUE TITLE
Spaces in keywords defined in python not recognized

### ISSUE THREAD

**Issue by rmxro** [millennialmedia/intellibot#152]
OK, I admit we have an unusual setup but Robot supports this by default.
If I have a keyword defined in a Python library like this:
def getGeneratedId(self):

and then call it in a Robot test like this:
Get Generated Id

Robot framework is able to link it back to the python method but IntelliBot is unable to find the keyword definition and as such I can't take advantage of all the features the plugin brings.

Please consider this as an enhancement in a future version, thanks!

**Comment by mtrubs** [comment]
i believe this is fixed as of 0.9.x
