### ISSUE TITLE
Variable definition not found for multiline [Arguments] setting

### ISSUE THREAD

**Issue by Sparrowbe** [millennialmedia/intellibot#154]
Intellibot marks as *Variable definition not found* error all usages of keyword's arguments that are defined below the first line of [Arguments] setting.
In the example below, "my_argument_2" and "my_argument_3" are properly used by pybot, but not resolved in Pycharm:

    Keyword with arguments
        [Arguments]  ${my_argument_1}=abc
        ...          ${my_argument_2}=def
        ...          ${my_argument_3}=ghi
        LOG MANY    ${my_argument_1}    ${my_argument_2}    ${my_argument_3}

**Comment by mtrubs** [comment]
#156
