### ISSUE TITLE
Standard RIDE variables not defined by intellibot

### ISSUE THREAD

**Issue by CMTaylor** [millennialmedia/intellibot#158]
If you transition from RIDE editing to intellibot editing of Robot Framework test cases, you lose all the pre-defined variables that RIDE supports. These should be supported in intellibot, too. For example:
${OUTPUT_DIR}
${True}
${False}
${EMTPY}
...

**Comment by mtrubs** [comment]
I have just recently implemented these.  I just have not released it yet.  I will try and put together the release this coming week.

See #150
