### ISSUE TITLE
Built-in variables show as errors (RobotFramework 3.0)

### ISSUE THREAD

**Issue by Jakub-CZ** [millennialmedia/intellibot#162]
[Built-in variables](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id509) are not recognized. Instead, "Variable definition not found" error is displayed.

**Examples:**
* ``${80}``
* ``${true}``
* ``${null}``
* ``${SPACE}``

**Comment by mtrubs** [comment]
are you suing the latest? 0.9.x?  and is your python setup correctly?

something like `${80}` will not work yet.  but everything else like `${true}` and such is supported.

**Comment by Jakub-CZ** [comment]
I've got version 0.9.143.381.

Python should be setup correctly; my Python projects work fine, and Inspection and Jump to Source from Robot to Python classes work fine too.

Do I need to include any Robot library in the Robot source for the plugin to pick up the built-in variables?

**Comment by mtrubs** [comment]
OH! Hahah, yes.  I never mentioned that in my python setup documentation.  Sure would be helpful.  The include that we use in pypi was `robotframework==2.7.7`.  Any version should work though.  You should end up with a robot directory in your site packages for the version of python you are using in your IDE.

Let me know and I will update the doc and we can close this.

**Comment by Jakub-CZ** [comment]
I'm confused. What I meant was whether I need to add something in the ``*** Settings ***`` section, like:
``Library       BuiltIn``

Btw. I'm on Windows. I have installed robotframework 3.0 via ``pip``. I installed your plugin directly through IntelliJ (current version) after removing the other Robot plugins which did't work for me at all (limited code completion, no Jump to Source of user keywords).
I'm not very experienced with Python and its inner workings.

**Comment by mtrubs** [comment]
No. the `builtin` library works special compared to others.  you should not have to include it in your `settings` section.  So the simple test is to open a python file in IntelliJ. if it compiles correctly then you have python setup for IntelliJ.  If you can include the robot library and reference one of the built in functions in the py file then you have it correct in your site-packages.  If you can include other python keywords in your robot files (which I think you said you can) then it is possible that robotframework 3.0 is different (which would be unfortunate for me).  I can also try and install 3.0 it and see.

**Comment by mtrubs** [comment]
so when I installed 3.0, all the built in keywords still work.  The variables are not found though so I need to find where they live now and add a check for those using 3.0.

If you cannot use the builtin keywords (like `log') then your IDE still has some kind of issue.

**Comment by Jakub-CZ** [comment]
I can compile Python files. I can include the robot library; I'm using ``logger`` from ``robot.api``. And I can include my Python classes, and successfully execute keywords implemented there. Even ``Ctrl+click`` on a keyword in the Robot source brings me to its Python implementation.

The built-in keywords work fine for me, so it's really only about those built-in variables.

**Comment by mtrubs** [comment]
yep that is what I was thinking once I put it all together...  its unfortunate.

I do have this fixed and working locally.  Let me pull the code in here.

**Comment by mtrubs** [comment]
#163

If you are using intellij 15+ you can install and test this manually.  I cannot build the earlier version right now and thus cannot push things to jet brains yet.  I will try to do so this weekend to correct things.

https://github.com/millennialmedia/intellibot/raw/master/intellibot.jar

**Comment by mtrubs** [comment]
also thank you for your quick responses.  made getting to the root of things much faster. 👍

**Comment by Jakub-CZ** [comment]
Thanks for the quick fix. I don't have the environment available right now. I'll try to set it up quickly again, and to validate the fix.

**Comment by Jakub-CZ** [comment]
I can confirm that the fixed version works for the built-in global variables now.

The numbers entered using the syntax of variables, e.g. ``${80}``, is not as critical as the actual variables were. I didn't find what version of Robot introduced this format, although it seems that version 2.7.7 did support those already.

**Comment by daize1994** [comment]
i use the last version of plugin with robotframework 3.0,it also have a problem,you see next pic:
![qq20160505-1](https://cloud.githubusercontent.com/assets/12844148/15040424/3fda6c2e-12e7-11e6-922c-8717d4cadaec.png)
I use the "${CURDIR}" to set my custom library,and it is not  get error,but it's seem not working,because my custom library's keywords still get "Undefined"

**Comment by mtrubs** [comment]
#163
