### ISSUE TITLE
WITH NAME feature not working for packages

### ISSUE THREAD

**Issue by adommisse4c** [millennialmedia/intellibot#165]
Assuming that Selenium2Library is in the python path and present in the Libs folder in the project.

**s2l.set selenium speed** is clickable and navigates to the python code.
**ls2l** (keyword definition not found)

```robot
*** Settings ***
Library   Selenium2Library  WITH NAME  s2l
Library   Libs.Selenium2Library    WITH NAME  ls2l

*** Test Cases ***
Test Direct
    s2l.set selenium speed   1

Test Lib
    ls2l.set selenium speed   1
```

Test passes using Robot 3.0

Using version 0.9.143.381 and PyCharm Community Edition 2016.1.2
Build #PC-145.844, built on April 8, 2016
JRE: 1.8.0_60-b27 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

**Comment by mtrubs** [comment]
Does `Libs.Selenium2Library` resolve?  I am wondering if I do not have my project setup quite correctly for it to do so?

This is what I see.  But the fact that `ls2l.set selenium speed` is not found is because `Libs.Selenium2Library` is not found.
```
*** Settings ***
          # resolves
Library   Selenium2Library  WITH NAME  s2l1
          # resolves
Library   Selenium2Library  WITH NAME  s2l2
          # does not resolve
Library   Libs.Selenium2Library    WITH NAME  ls2l

*** Test Cases ***
Test Direct 1
    # resolves
    s2l1.set selenium speed   1
    
Test Direct 2
    # resolves
    s2l2.set selenium speed   1

Test Lib
    # does not resolve
    ls2l.set selenium speed   1
```

**Comment by mtrubs** [comment]
Here is another example.  I think the issue (in this case) is that `test.Demo` does not resolve in the IDE (and `Libs.Selenium2Library` in yours).  I think you saying if we use pybot it will...?

```
*** Settings ***
                  # resolves
Library           Demo  WITH NAME  d1
                  # resolves
Library           Demo  WITH NAME  d2
                  # resolves
Library           test.demo.Demo  WITH NAME  ld1
                  # does not resolve
Library           test.Demo  WITH NAME  ld2

*** Keywords ***

something
    # resolves
    demo result1
    # resolves
    d1.demo result1
    # resolves
    d2.demo result1
    # resolves
    ld1.demo result1
    # does not resolve
    ld2.demo result1
```

**Comment by adommisse4c** [comment]
It is correct that Libs.Selenium2Library does not resolve. Somehow it does run here (in RIDE). 
If I use a different library (a page object library), that does resolve (and is navigatable with CTRL+click) it still doesn't work. However, our setup is quite convoluted, so something might happen there.

Since this involves libraries, I think it might help it I set up a small project that illustrates this. I'll try to do this tomorrow.

**Comment by adommisse4c** [comment]
I've made a separate project:
https://github.com/adommisse4c/robot_with_name_test


![image](https://cloud.githubusercontent.com/assets/17175839/15009124/f4079266-11e4-11e6-922c-75e5ac2d5094.png)

However, it does run when I run robot from the shell

```powershell
PS C:\Users\adommiss\PycharmProjects\robot_with_name_test> python -m robot Robot\test.robot
==============================================================================
Test
==============================================================================
Test Single File With Name                                            | PASS |
------------------------------------------------------------------------------
Test Module                                                           | PASS |
------------------------------------------------------------------------------
Test Module With Name                                                 | PASS |
------------------------------------------------------------------------------
Test                                                                  | PASS |
3 critical tests, 3 passed, 0 failed
3 tests total, 3 passed, 0 failed
==============================================================================
Output:  C:\Users\adommiss\PycharmProjects\robot_with_name_test\output.xml
Log:     C:\Users\adommiss\PycharmProjects\robot_with_name_test\log.html
Report:  C:\Users\adommiss\PycharmProjects\robot_with_name_test\report.html
```

**Comment by mtrubs** [comment]
perfect.  thank you. I will see were this takes me.  Thank you again for your efforts on helping this.

**Comment by Tillaert** [comment]
Apparently there are two ways to import a test library into robot:

```robot
*** Settings ***
Library    test_module.testfile.testfile    WITH NAME    tm
Library    test_module.testfile     WITH NAME    tm2

*** Test Cases ***
Test Module With Name With Class
    tm.test keyword
    # Is parsed correctly by intellibot

Test Module With Name Without Class
    tm2.test keyword
    # Is parsed incorrectly by intellibot 
```
Both test cases pass in robot.

If there is no class specified then robot will import the class that has the same name as the file (in this case the **class** `test_file` in the **file** `test_file`. 

This behavior is probably caused by: src:com/millennialmedia/intellibot/psi/ref/RobotPythonFile.java:59

```java
        for (PyClass subClass : this.pythonFile.getTopLevelClasses()) {
            String namespace = subClass.getQualifiedName() == null ? EMPTY : subClass.getQualifiedName();
            addDefinedKeywords(subClass, namespace, results);
        }
```

`subClass.getQualifiedName()` always returns the full name (here: `test_module.testfile.testfile`) while tm2 is associated with `test_module.testfile`. This causes the function not to be found.

A better example:

```robot
*** Settings ***
Library    testmodule.testfile

*** Test Cases ***
Resolved by intellibot but fails in Robot
    testmodule.testfile.testfile.test keyword

Not resolved by intellibot but passes in Robot
    testmodule.testfile.test keyword
```

(I had to remove the underscore in test_module, intellibot doesn't resolve correctly if there are underscores in the module name, but that's another issue. Underscores are allowed according to PEP 8)

This is caused by com.millennialmedia.intellibot.psi.util.PatternUtil.functionToKeyword, which replaces all underscores in the QualifiedName with spaces, and thus mangles the module/class name.

**Comment by Tillaert** [comment]
Same issue as Issue #157

**Comment by mtrubs** [comment]
#166
