### ISSUE TITLE
Feature request/bug: robot.api.deco @keyword support

### ISSUE THREAD

**Issue by Tillaert** [millennialmedia/intellibot#167]
Robot can use the `@keyword` decorator (see http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-decorators)

When this decorator is present, robot uses that, and ignores the function name.

Intellibot incorrectly points to the function name.

**Comment by mtrubs** [comment]
Is this something we should add to the Robot Options? ie turn on and off? or is it more if the decorator is there it is always used?

https://github.com/millennialmedia/intellibot/wiki/Robot-Options

**Comment by mtrubs** [comment]
... looking at the doc i wish we knew about that when we started. cleans up the code nicely.

**Comment by Tillaert** [comment]
If the @keyword is used, then robot will only resolve the @keyword and
current function. We could make it configurable, with default on?

**Comment by Tillaert** [comment]
Correction: robot will only resolve @keyword and NOT the function name. So
currently intellibot resolves the incorrect name.

@keyword("decorated")
def non_decorated(self):
    pass

Robot resolves: decorated
Intellibot resolves: non_decorated

**Comment by mtrubs** [comment]
if robot will not resolve it then perhaps the configuration is unnecessary.

**Comment by mtrubs** [comment]
#169
