### ISSUE TITLE
Support for .resource files

### ISSUE THREAD

**Issue by cooper-a** [millennialmedia/intellibot#209]
Robot Framework now supports .resource file naming of files. This plugin should treat .resource files the same as .robot files. It should be an easy fix.

**Comment by cooper-a** [comment]
Never mind, I realized it can files can just be changed within PyCharm.

**Comment by stdedos** [comment]
Doesn't matter. Why the plugin cannot register it itself?

Please re-open

**Comment by doyou89** [comment]
The plugin cannot index .resource files. So need to re-open.

**Comment by DvaKompota** [comment]
> Never mind, I realized it can files can just be changed within PyCharm.

Could you please explain what you've meant? 
Refactoring/renaming using PyCharm?
So the solution is not to use .resource extension, but only .robot?
