### ISSUE TITLE
Intellibot does not see my python keywords

### ISSUE THREAD

**Issue by skipkent** [millennialmedia/intellibot#50]
Libraries imported from python keyword files are now being flagged in Pycharm as 'Import file not found'.  This began to occur after upgrading to the latest Intellibot plugin.

Here's an example import line, in this case for a python keyword file which is in the same directory as the the Robot script that uses it:

Library                ./performanceKeywords.py

The file is still there and the robot script runs fine, but intellibot appears to be missing it somehow.

**Comment by blwillia** [comment]
I'm having the exact same issue with PyCharm 5.0.4

Not sure what's happening but all of my resource files are not appearing in intellibot.
![capture](https://cloud.githubusercontent.com/assets/2389006/12854424/4d83ede8-cbff-11e5-9266-d00cf61669e5.JPG)

**Comment by AjitJ01** [comment]
@skipkent @blwillia I'm also having same issue ...please let me knoww if you gus found workarround. Thanks.
Ajit J
