### ISSUE TITLE
support built in variables

### ISSUE THREAD

**Issue by mtrubs** [millennialmedia/intellibot#58]
${TEMPDIR}
${EXECDIR}
${/}
${:}
${\\n}
${SPACE}
${EMPTY}
@{EMPTY}
${True}
${False}
${None}
${null}
${OUTPUT_DIR}
${OUTPUT_FILE}
${REPORT_FILE}
${LOG_FILE}
${DEBUG_FILE}
${PREV_TEST_NAME}
${PREV_TEST_STATUS}
${PREV_TEST_MESSAGE}

**Comment by yahman72** [comment]
This would be a great improvement - have you also thought about the code completion of "normal" variables?

E.g.
<pre>
${foo} =   Set Variable    bar
$
</pre>
After typing "$" the code completion could offer a list of defined variables (buildIn and user variables)...

**Comment by mtrubs** [comment]
yes. code completion for variables will be a part of the next release (which has already been submitted to JetBrains).

**Comment by yahman72** [comment]
That's great news, thanks!

**Comment by mtrubs** [comment]
closing in favor of #150
