### ISSUE TITLE
Code check is not finding python keywords in sub-class

### ISSUE THREAD

**Issue by skipkent** [millennialmedia/intellibot#65]
I'm not sure if I described this properly in the title, but hopefully this example code snippet will help.

    from robot.libraries.BuiltIn import BuiltIn
    from Selenium2Library.keywords.keywordgroup import KeywordGroup
    import logging

    def get_current_browser():
        browser = BuiltIn().get_library_instance('Selenium2Library')._current_browser()
        return browser

    class MyLibrary(KeywordGroup):

        def get_title_via_python(self):
            driver = get_current_browser()
            title = driver.title
            logging.warn("checking title %s" % title)
            return title

In PyCharm, a Robot file that uses this python library file (import is successfully acknowledged by Intellibot) will show that 'Get Current Browser' resolves to the python code, but 'Get Title Via Python' does not, and is instead lined in red with a 'Keyword definition not found' error.

**Comment by mtrubs** [comment]
#110
