### ISSUE TITLE
Variable in text color is not working

### ISSUE THREAD

**Issue by pchomik** [millennialmedia/intellibot#68]
Variable settings in Editor Color & Text is not working. Variable used in the test body has color of argument.

**Comment by iradovanovic** [comment]
+1 for me.

**Comment by mtrubs** [comment]
this will be fixed once I complete #96

**Comment by pchomik** [comment]
Great. Thanks

-----Wiadomość oryginalna-----
Od: "Matthew Rubino" <notifications@github.com>
Wysłano: ‎2015-‎07-‎24 16:00
Do: "millennialmedia/intellibot" <intellibot@noreply.github.com>
DW: "Pawel Chomicki" <pawel.chomicki@gmail.com>
Temat: Re: [intellibot] Variable in text color is not working (#68)

this will be fixed once I complete #96

**Comment by mtrubs** [comment]
done.
