### ISSUE TITLE
Relative import for class search doesn't works  

### ISSUE THREAD

**Issue by catchayaz** [millennialmedia/intellibot#72]
Consider a python library file written in class structure let say Library.py
Now if this file is in Pythonpath or in current directory the import works fine, i.e.
*** Settings ***
Library  Library

if the same file is imported with relative path, i.e
*** Settings ***
Library  Path1/Path2/Library
Library.py is detected, but the keywords present inside is not detected i.e. class search didn't worked.

**Comment by catchayaz** [comment]
It's looks like as do-able as the other plugin was able to work properly in above scenario
https://github.com/AmailP/robot-plugin

**Comment by mtrubs** [comment]
this appears to be working correctly now.
