### ISSUE TITLE
assign multiple variables at once not recognised

### ISSUE THREAD

**Issue by laurentbristiel** [millennialmedia/intellibot#73]
In Robot it possible to assign multiple variable at once. 
For example:
```
*** Test Cases ***
my_test
    ${status}  ${value} =  Run Keyword And Ignore Error  My Keyword
```
This is not recognised by the plugin: second variable is interpreted as a keyword:
![two_variables](https://cloud.githubusercontent.com/assets/4035242/4056573/c18cfc8a-2dbc-11e4-8f64-953e63eb9009.png)

**Comment by mtrubs** [comment]
#91, just need to triple check the lexer changes as they always make me cautious.
