### ISSUE TITLE
Incorrect "Keyword definition not found" errors for Robot Libraries in PyCharm

### ISSUE THREAD

**Issue by rusitzky** [millennialmedia/intellibot#77]
Keywords from the standard Robot Libraries are incorrectly being identified with "Keyword definition not found" errors.  For example:

>  *** Settings ***
>  Library     Process

>  *** Test Cases ***
>  Simple Check
>    ${result} =   Run Process  date
>    Should Not Be Empty  ${result.stdout}

will show that "Run Process" has the error "Keyword definition not found."  I'm using PyCharm Community Edition 4.0.3 and have tried IntelliBot 0.6.4 & 0.6.5.

**Comment by zherebjatjew** [comment]
That happens for all embedded keywords:
![embedded-keywords](https://cloud.githubusercontent.com/assets/1769330/7152723/84162508-e35a-11e4-933c-356b83acf1e0.png)

**Comment by orlof** [comment]
I think I had this same problem (in osx) and I was able to fix it by fiddling with IntelliJ settings and project structure. The bad news is that I am not sure which change finally solved the issue. My best guess is to change the python SDK in platform settings to:
Python 2.7.9 (/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7)
(I used to have /usr/bin/python instead) But I am not familiar with os-x and I may be totally wrong here.

**Comment by markwinspear** [comment]
I found the same issue and couldn't solve it. Unfortunately I had to uninstall intellibot and use Robot Framework Support plugin for PyCharm instead

**Comment by mtrubs** [comment]
see this wiki page regarding interpreter setup in pycharm: https://github.com/millennialmedia/intellibot/wiki/Python-Interpreter

**Comment by splintor** [comment]
I also have this problem (in IntelliJ). Configuring Python in the link provided by @mtrubs doesn't really help.

**Comment by splintor** [comment]
However, this only works if the file has *** Settings *** line at its header. If it is a keywords file, that doesn't have it, the builtins keyword are not recognized, for some reason. Should I open a different issue for that?

**Comment by mtrubs** [comment]
I think I see what you are saying.  If you do not have a Setting header then the plugin will not find built in python keywords like it should.  Yes this would be a different issue.  I think that might just be a matter of how I handle the imports.

**Comment by splintor** [comment]
Thanks. Opened #153 for this.

**Comment by mtrubs** [comment]
I updated the wiki page, hopefully it is more clear...

https://github.com/millennialmedia/intellibot/wiki/Python-Interpreter

**Comment by AjitJ01** [comment]
Unable to jump on parameterzed keywords and keywords in .py files.
