### ISSUE TITLE
Release a new version to plugins.jetbrains.com

### ISSUE THREAD

**Issue by ate-f** [millennialmedia/intellibot#78]
Hi,

We are using intellibot and would like to make advantage of the bugfixes that were introduced after 0.6.4. Of course, it's possible to compile intellibot ourselves, however previous attempts showed this does not simply 'work' (to add a change we made I resorted to editing the jar instead of compiling the project since I couldn't get it to work).  Since you've already updated the version it would seem logical to either update the repository, or provide a new jarfile for manual install. At the moment the jar file is 7 months old.

Regards,
Ate

**Comment by pchomik** [comment]
+1

**Comment by thanasis00** [comment]
+1

**Comment by mtrubs** [comment]
uploaded.
