### ISSUE TITLE
doesn't work with pycharm ce in OS X yosemite

### ISSUE THREAD

**Issue by rkhozinov** [millennialmedia/intellibot#80]
![screen shot 2015-02-26 at 23 37 29](https://cloud.githubusercontent.com/assets/1063498/6401301/75896a64-be10-11e4-861f-52e9eac473e4.png)
![screen shot 2015-02-26 at 23 36 03](https://cloud.githubusercontent.com/assets/1063498/6401277/528f1306-be10-11e4-94ff-f8b7765131d1.png)

Java for OS X 2014-001 includes installation improvements, and supersedes all previous versions of Java for OS X. This package installs the same version of Java 6 included in Java for OS X 2013-005.

**Comment by pmhalder** [comment]
having the same issue . please respond

**Comment by jcdevil** [comment]
I have the same issue (working with Community Edition) also : it seems the problem is linked to the fact that PyCharm is delivered with Java 6 and the plugin with Java 7 (or higher ?)
1 workaround it to change the java used by PyCharm... but also waiting for the official fix :)

**Comment by pmhalder** [comment]
thank you so much @jcdevil . you saved my Day .

**Comment by mtrubs** [comment]
can you try this plug-in (install from disk) this would be the same artifact that I would upload to jet brains provided it fixes things. 

https://github.com/millennialmedia/intellibot/raw/6cb8c9514990dbfc23982e385b15d3252c1e3e96/intellibot.jar

**Comment by mtrubs** [comment]
#87
