### ISSUE TITLE
False 'Unused import statement' reports

### ISSUE THREAD

**Issue by zherebjatjew** [millennialmedia/intellibot#83]
```
*** Settings ***
Resource          EmsServer_Keywords.txt
Resource          EmsClient_Keywords.txt

Test_Simple
    ${path} =           Set variable    path
    ${entitlement} =    build entitlement with id "1" and pathCondition "${path}"
```
The 'build entitlement with id..' is defined in EmsClient_Keywords.txt, the plugin opens it by ctrl+click, but reports 'unused import statement' for this resource.

**Comment by mtrubs** [comment]
I believe this should be fixed with the latest artifact (0.6.7, pushed to the jet brains repo's 2015-08-30)
