### ISSUE TITLE
False 'Variable defination not found' reports

### ISSUE THREAD

**Issue by molsky** [millennialmedia/intellibot#85]
I got `Variable defination not found` for every possible variable, even for Robot Framework's built-in variables like `${EMPTY}`.
```
*** Variables ***
${new_first}=  Robot
${new_last}=  Testaaja

*** Test Cases ***
Check Something and Do Something
    Element Text Should Be  element_id  ${new_first}  ${new_last}
    Input Text  another_element_id  ${EMPTY}
```
Even in this scenario I got errors about variable defination not found.

PyCharm 4.0.6
OSX 10.9.5

**Comment by orlof** [comment]
I just found intellibot couple of days ago, so I am definitely not an expert, but I just tested your example (IntelliJ IDEA 14.1.2, OSX  10.10.2). Variable detection and 'click into' are working perfectly, but the built in variables seems not to be supported at the moment. Are your keywords working properly?

...On the other hand I still haven't got variable detection working between files.

**Comment by molsky** [comment]
It doesn't recognize global variables in resource files. Also if the variables are created in test case and set global using BuiltIn library's keywords it doesn't recognize them either. And syntax highlighting for variables that are used as keywords parameter is broken,  for example: ´Input Text  company_id  ${company}´.

**Comment by MikeBeardman** [comment]
Hey,

This is partially fixed in my pull request: https://github.com/millennialmedia/intellibot/pull/89

This will resolve variables in resource files.  I'm planning to add support for global variables and variables that are used in other variable declarations.

**Comment by mtrubs** [comment]
Ill get @MikeBeardman's changes out soon.  It is true that global variables are not currently supported.

**Comment by mtrubs** [comment]
I believe with @MikeBeardman this is all resolved (except for built in variables which is https://github.com/millennialmedia/intellibot/issues/58)

**Comment by fmandy** [comment]
I am still getting this today, with the latest released version of intellibot, robotframework and pycharm.   Global variables defined in the *** Variables *** section of my main test.robot are reporting "Variable definition not found" in resource and page object files that are correctly referenced "Resources".  The script runs correctly, but the error messages are still there.
