### ISSUE TITLE
Pycharm pro 4 crash on startup

### ISSUE THREAD

**Issue by serhatbolsu** [millennialmedia/intellibot#86]
Error : 
com.intellij.diagnostic.PluginException: com/millennialmedia/intellibot/psi/RobotPsiManager:Unsupported major.minor version 51.0

**Comment by mtrubs** [comment]
can you try this plug-in (install from disk) this would be the same artifact that I would upload to jet brains provided it fixes things. 

https://github.com/millennialmedia/intellibot/raw/6cb8c9514990dbfc23982e385b15d3252c1e3e96/intellibot.jar

**Comment by serhatbolsu** [comment]
Hey,

I fixed the error after I did the change of pycharm using java 1.7 .

Thank you for the update, I will try to check when I have chance

**Comment by mtrubs** [comment]
#87
